export const calendarEvents = [
  {
    id: 'event-reflexology',
    title: 'Reflexology',
    type: 'event',
    date: '2026-05-18',
    startTime: '10:30',
    endTime: '12:30',
    location: 'She-Na Treatment Room',
    description: 'Gentle foot-based touch therapy for balance, relaxation, and inner resilience.',
    registered: false,
  },
  {
    id: 'event-womens-circle-day-after',
    title: "Women's Circle - The Day After",
    type: 'registration',
    date: '2026-05-18',
    startTime: '19:30',
    endTime: '21:00',
    location: 'Community Circle Room',
    description: 'A supportive women-centered space for sharing, listening, connection, and healing.',
    registered: true,
  },
  {
    id: 'event-qigong',
    title: 'Qigong',
    type: 'event',
    date: '2026-05-19',
    startTime: '17:00',
    endTime: '18:00',
    location: 'Movement Studio',
    description: 'Soft movement and breathing practice for release, energetic balance, and body-mind strength.',
    registered: false,
  },
  {
    id: 'event-yoga',
    title: 'Yoga',
    type: 'event',
    date: '2026-05-20',
    startTime: '10:30',
    endTime: '11:30',
    location: 'Yoga Studio',
    description: 'Adapted yoga practice combining mindful movement, breathing, and deep relaxation.',
    registered: false,
  },
  {
    id: 'event-acupuncture-herbal-medicine',
    title: 'Acupuncture & Herbal Medicine',
    type: 'event',
    date: '2026-05-20',
    startTime: '10:30',
    endTime: '12:30',
    location: 'Chinese Medicine Room',
    description: 'Traditional Chinese medicine care for balance, symptom relief, and overall strengthening.',
    registered: false,
  },
  {
    id: 'appointment-couples-counseling',
    title: 'Couples Counseling',
    type: 'appointment',
    date: '2026-05-21',
    startTime: '10:00',
    endTime: '11:00',
    location: 'Private Counseling Room',
    description: 'Guided emotional, practical, and communication-focused support for strengthening the relationship.',
    registered: true,
  },
];

export const calendarNotes = [
  {
    id: 'note-check-in',
    title: 'Schedule note',
    date: '2026-05-22',
    startTime: '13:00',
    endTime: '13:30',
    content: 'NLP Therapy, NLP Supportive Touch, and Lilach Fisher session are still waiting for final scheduling.',
  },
];

export const calendarFirestoreCollections = {
  events: 'Public workshops and activities available to participants.',
  registrations: 'Participant event registrations linked by participantId and eventId.',
  appointments: 'Future participant appointments such as psychologist or massage sessions.',
  calendar_notes: 'Participant-created private calendar notes linked by participantId.',
};
